### PR TITLE
Fix incorrect escaping of URL parameters.

### PR DESCRIPTION
**Pull request by mr-russ**
We are escaping data elements as part of the Query parameter escaping.  So use EscapeDataString, which is for that purpose.

See: https://stackoverflow.com/questions/4396598/whats-the-difference-between-escapeuristring-and-escapedatastring

For a discussion on the implications.

### CODE REVIEW

**Comment by mr-russ** [comment]
@github-anurag that was signed yesterday with 30 minutes of the request.  There must be something inside Oracle holding it up.  What can I do to resolve that?

**Comment by mr-russ** [comment]
@github-anurag I'm currently unable to migrate to Oracle Storage as our prefixes contain the # character.  The incorrect escaping mean that we can't list objects.  There may be other implication, but I can't verify those as attempting to get file lists fails.

**Review by github-anurag — APPROVED** [review]

**Comment by github-anurag** [comment]
@mr-russ 
These are the instructions that I see for signing the OCA:-

The following contributors of this PR have not signed the OCA:

PR author: mr-russ
[russell.smith@cornerstonesolutions.com.au](mailto:russell.smith@cornerstonesolutions.com.au) (@mr-russ)
To sign the OCA, please [create an Oracle account](https://profile.oracle.com/myprofile/account/create-account.jspx) and sign the OCA in [Oracle's Contributor Agreement Application](https://oca.opensource.oracle.com/).

Can you check if you created the Oracle account with the same email account?

**Comment by Djelibeybi** [comment]
@mr-russ the email address you signed the OCA with doesn't match the email address in the PR, which is why this is not being passed by the OCA bot. Can you please either modify your PR to be submitted by the same email address as your signed OCA or perhaps add your email address to your Oracle account?

**Comment by mr-russ** [comment]
github did not choose my primary email.  there is no way to "update" a pull request.  I will be probably opening multiple pull requests while adjusting my profile to get it in the "right" state.  That may however create issues in the future.   Email addresses change, my account does not.  But I'll see what I can do.

**Comment by mr-russ** [comment]
PR #248  was my next attempt, but it still shows an email that is no longer on my account and that I don't have access to.

**Pull request closed without merging**
